server:
  port: 8092
  servlet:
    context-path: /todo

spring:
  application:
    name: TodoApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/Todo?createDatabaseIfNotExist=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect

    main:
      web-application-type: none

swagger:
  url: http://localhost:8092/todo

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: https://service-registry.test.restaurantonesolution.com/eureka/
#  instance:
#    hostname: 20.90.96.90

#logging:
#  file:
#    name: todo.log
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"
#  level:
#    "[org.springframework.web]": INFO
#    "[com.ros.inventory]": DEBUG
#    "[org.hibernate]": INFO

#admin:
#  url: https://administrationservice.test.restaurantonesolution.com/admin


